name: pullapp
description: A new Flutter project.




version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.0

dev_dependencies:
  decimal: ^0.3.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - images/
    - images/pierna.jpg
    - images/cinta.jpg
    - images/cinta2.jpg
    - images/pecho.jpg
    - images/abdominal.jpg
    - images/peso.jpg
    - images/espalda.jpg
    - images/gluteos.jpg
    - images/gluteos2.jpg
    - images/barra.jpg
    - images/mancuernas.jpg
    - images/estiramiento.jpg

  
